# Generated by Django 3.2.3 on 2021-05-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apx', '0002_usermoviewatched'),
    ]

    operations = [
        migrations.CreateModel(
            name='moviesData',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('imdbID', models.IntegerField()),
                ('year', models.IntegerField()),
                ('rtPictureURL', models.URLField()),
            ],
        ),
    ]
