# Generated by Django 3.2.3 on 2021-05-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apx', '0004_moviesgenre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesgenre',
            name='imdbID',
        ),
        migrations.RemoveField(
            model_name='moviesgenre',
            name='rtPictureURL',
        ),
        migrations.RemoveField(
            model_name='moviesgenre',
            name='year',
        ),
        migrations.AddField(
            model_name='moviesgenre',
            name='genres',
            field=models.CharField(default='NULL', max_length=800),
            preserve_default=False,
        ),
    ]
